<?xml version="1.0"?>

<!DOCTYPE music [
<!ELEMENT attends(attend*)>
<!ELEMENT venues(venue*)>
<!ELEMENT users(user*)>
<!ELEMENT events(event*)>
<!ELEMENT likes(like*)>
<!ELEMENT organizers(organizer*)>
<!ELEMENT topics(topic*)>
<!ELEMENT categories(category*)>

<!ELEMENT attend(created_at, updated_at, user_id, event_id)>
<!ELEMENT venue(created_at, updated_at, id, name, address, zip, phone)>
<!ELEMENT user(created_at, updated_at, f_name, l_name, b_day, gender, email, password, address,city, state, zip, phone, remember_token)>
<!ELEMENT event(created_at, updated_at, id, when, name, topic_id, venue_id, organizer_id, description)>
<!ELEMENT like(created_at, updated_at, user_id, topic_id)>
<!ELEMENT organizer(created_at, updated_at, id, name, email, phone)>
<!ELEMENT topic(created_at, updated_at, id, name, category_id, description)>
<!ELEMENT category(created_at, updated_at, id, name, description)>

<!ELEMENT created_at(#PCDATA)>
<!ELEMENT updated_at(#PCDATA)>
<!ELEMENT id(#PCDATA)>
<!ELEMENT user_id(#PCDATA)>
<!ELEMENT event_id(#PCDATA)>
<!ELEMENT name(#PCDATA)>
<!ELEMENT address(#PCDATA)>
<!ELEMENT zip(#PCDATA)>
<!ELEMENT phone(#PCDATA)>
<!ELEMENT f_name(#PCDATA)>
<!ELEMENT l_name(#PCDATA)>
<!ELEMENT b_day(#PCDATA)>
<!ELEMENT gender(#PCDATA)>
<!ELEMENT email(#PCDATA)>
<!ELEMENT password(#PCDATA)>
<!ELEMENT address(#PCDATA)>
<!ELEMENT city(#PCDATA)>
<!ELEMENT state(#PCDATA)>
<!ELEMENT remember_token(#PCDATA)>
<!ELEMENT when(#PCDATA)>
<!ELEMENT topic_id(#PCDATA)>
<!ELEMENT venue_id(#PCDATA)>
<!ELEMENT organizer_id(#PCDATA)>
<!ELEMENT description(#PCDATA)>
<!ELEMENT category_id(#PCDATA)>
]>

<music>
	<attends>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>1</user_id>
			<event_id>0</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>1</user_id>
			<event_id>1</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>10</user_id>
			<event_id>18</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>10</user_id>
			<event_id>19</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>12</user_id>
			<event_id>2</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>12</user_id>
			<event_id>6</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>12</user_id>
			<event_id>9</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>12</user_id>
			<event_id>20</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>19</user_id>
			<event_id>9</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>2</user_id>
			<event_id>10</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>2</user_id>
			<event_id>17</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>2</user_id>
			<event_id>20</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>20</user_id>
			<event_id>8</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>20</user_id>
			<event_id>11</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>20</user_id>
			<event_id>18</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>3</user_id>
			<event_id>12</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>3</user_id>
			<event_id>15</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>5</user_id>
			<event_id>2</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>6</user_id>
			<event_id>14</event_id>
		</attend>
		<attend>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>8</user_id>
			<event_id>16</event_id>
		</attend>
	</attends>
	<categories>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>1</id>
			<name>Alternative Rock</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>2</id>
			<name>Hard Rock</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>3</id>
			<name>Indie Rock</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>4</id>
			<name>Classic Rock</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>5</id>
			<name>Punk</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>6</id>
			<name>Blues</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>7</id>
			<name>Classical</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>8</id>
			<name>Country</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>9</id>
			<name>Trance</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>10</id>
			<name>Dubstep</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>11</id>
			<name>House</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>12</id>
			<name>Techno</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>13</id>
			<name>Pop</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>14</id>
			<name>Rap</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>15</id>
			<name>Hip-Hop</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>16</id>
			<name>Instrumental</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>17</id>
			<name>Jazz</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>18</id>
			<name>Nature</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>19</id>
			<name>Relaxation</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>20</id>
			<name>Meditation</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>21</id>
			<name>Reggae</name>
			<description xsi:nil="true" description>
		</category>
		<category>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>22</id>
			<name>Vocal</name>
			<description xsi:nil="true" description>
		</category>
	</categories>
	<events>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>1</id>
			<when>2014-12-01</when>
			<name>Bonaroo</name>
			<topic_id>1</topic_id>
			<venue_id>16</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>2</id>
			<when>2014-12-04</when>
			<name>Warped Tour</name>
			<topic_id>5</topic_id>
			<venue_id>6</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>3</id>
			<when>2014-12-07</when>
			<name>Electric Daisy Carnival</name>
			<topic_id>11</topic_id>
			<venue_id>12</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>4</id>
			<when>2015-01-08</when>
			<name>SXSW</name>
			<topic_id>1</topic_id>
			<venue_id>16</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>5</id>
			<when>2015-02-17</when>
			<name>iHeartRadio Music Festival</name>
			<topic_id>15</topic_id>
			<venue_id>1</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>6</id>
			<when>2015-02-22</when>
			<name>Coachella</name>
			<topic_id>14</topic_id>
			<venue_id>19</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>7</id>
			<when>2015-03-17</when>
			<name>Lollapalooza</name>
			<topic_id>5</topic_id>
			<venue_id>16</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>8</id>
			<when>2015-03-28</when>
			<name>iTunes Festival</name>
			<topic_id>15</topic_id>
			<venue_id>1</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>9</id>
			<when>2015-04-06</when>
			<name>Bamboozle</name>
			<topic_id>4</topic_id>
			<venue_id>9</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>10</id>
			<when>2015-04-21</when>
			<name>Highland Jazz Festival</name>
			<topic_id>17</topic_id>
			<venue_id>5</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>11</id>
			<when>2015-05-20</when>
			<name>Country Fest</name>
			<topic_id>8</topic_id>
			<venue_id>17</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>12</id>
			<when>2015-06-02</when>
			<name>Watershed Music Festival</name>
			<topic_id>6</topic_id>
			<venue_id>15</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>13</id>
			<when>2015-07-11</when>
			<name>Goodstock Music Festival</name>
			<topic_id>2</topic_id>
			<venue_id>16</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>14</id>
			<when>2015-07-17</when>
			<name>Decibel Festival</name>
			<topic_id>10</topic_id>
			<venue_id>13</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>15</id>
			<when>2015-08-01</when>
			<name>The Echo Project</name>
			<topic_id>9</topic_id>
			<venue_id>13</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>16</id>
			<when>2015-09-01</when>
			<name>Epicenter</name>
			<topic_id>7</topic_id>
			<venue_id>14</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>17</id>
			<when>2015-09-17</when>
			<name>Audiotistic Music Festival</name>
			<topic_id>18</topic_id>
			<venue_id>8</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>18</id>
			<when>2015-12-03</when>
			<name>DeltaFest</name>
			<topic_id>12</topic_id>
			<venue_id>12</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>19</id>
			<when>2015-12-12</when>
			<name>Krazy Fest</name>
			<topic_id>16</topic_id>
			<venue_id>8</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
		<event>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>20</id>
			<when>2015-12-31</when>
			<name>Atwood Music Festival</name>
			<topic_id>19</topic_id>
			<venue_id>8</venue_id>
			<organizer_id xsi:nil="true" ></organizer_id>
			<description xsi:nil="true" description>
		</event>
	</events>
	<likes>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>1</user_id>
			<topic_id>1</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>1</user_id>
			<topic_id>2</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>10</user_id>
			<topic_id>12</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>10</user_id>
			<topic_id>16</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>12</user_id>
			<topic_id>3</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>12</user_id>
			<topic_id>5</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>12</user_id>
			<topic_id>14</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>12</user_id>
			<topic_id>20</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>19</user_id>
			<topic_id>4</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>2</user_id>
			<topic_id>17</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>2</user_id>
			<topic_id>18</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>2</user_id>
			<topic_id>19</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>20</user_id>
			<topic_id>8</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>20</user_id>
			<topic_id>12</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>20</user_id>
			<topic_id>15</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>3</user_id>
			<topic_id>6</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>3</user_id>
			<topic_id>9</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>5</user_id>
			<topic_id>5</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>6</user_id>
			<topic_id>10</topic_id>
		</like>
		<like>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<user_id>8</user_id>
			<topic_id>7</topic_id>
		</like>
	</likes>
	<organizers>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>1</id>
			<name>SXSW Inc</name>
			<email>contactus@sxsw.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>2</id>
			<name>iHeartRadio</name>
			<email>contactus@iheartradio.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>3</id>
			<name>LiveNation</name>
			<email>help@livenation.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>4</id>
			<name>AEG Live</name>
			<email>events@aeglive.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>5</id>
			<name>Classical Movements</name>
			<email>info@classicalmovements.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>6</id>
			<name>Peter Shapiro</name>
			<email>peter@shapiro.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>7</id>
			<name>Roc Nation</name>
			<email>contactus@rocnation.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>8</id>
			<name>SFX Entertainment</name>
			<email>info@sfxii.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>9</id>
			<name>Stageco</name>
			<email>info.us@stageco.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>10</id>
			<name>Insomniac Events</name>
			<email>info@insomniac.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>11</id>
			<name>SM Global Union</name>
			<email>support@24hourhiphop.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>12</id>
			<name>Apple</name>
			<email>help@apple.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>13</id>
			<name>Superfly Presents</name>
			<email>info@superflymarketinggroup.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>14</id>
			<name>AC Entertainment</name>
			<email>info@acentertainment.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>15</id>
			<name>Americana Music Association</name>
			<email>info@americanamusic.org</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>16</id>
			<name>Goldenvoice</name>
			<email>info@goldenvoice.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>17</id>
			<name>Vans</name>
			<email>vanscustserv@vfc.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>18</id>
			<name>Virgin Group</name>
			<email>info@virgin.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>19</id>
			<name>Michael Lang</name>
			<email>michael@lang.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
		<organizer>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>20</id>
			<name>MusicHouse</name>
			<email>info@mhouse.com</email>
			<phone xsi:nil="true" phone>
		</organizer>
	</organizers>
	<topics>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>1</id>
			<name>Led Zeppelin</name>
			<category_id>4</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>2</id>
			<name>Pink Floyd</name>
			<category_id>4</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>3</id>
			<name>Katy Perry</name>
			<category_id>13</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>4</id>
			<name>Jason Derulo</name>
			<category_id>13</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>5</id>
			<name>Lorde</name>
			<category_id>13</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>6</id>
			<name>Pitiful</name>
			<category_id>15</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>7</id>
			<name>Avicii</name>
			<category_id>12</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>8</id>
			<name>Sam Smith</name>
			<category_id>23</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>9</id>
			<name>Eminem</name>
			<category_id>14</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>10</id>
			<name>Wolfgang Amadeus Mozart</name>
			<category_id>7</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>11</id>
			<name>James Blunt</name>
			<category_id>13</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>12</id>
			<name>Metallica</name>
			<category_id>5</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>13</id>
			<name>Adele</name>
			<category_id>23</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>14</id>
			<name>3 Doors Down</name>
			<category_id>2</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>15</id>
			<name>AC/DC</name>
			<category_id>2</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>16</id>
			<name>Iron Maiden</name>
			<category_id>5</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>17</id>
			<name>John Mayer</name>
			<category_id>7</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>18</id>
			<name>Nirvana</name>
			<category_id>1</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>19</id>  
			<name>Red Hot Chilli Peppers</name>
			<category_id>1</category_id>
			<description xsi:nil="true" description>
		</topic>
		<topic>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<id>20</id>
			<name>Taylor Swift</name>
			<category_id>9</category_id>
			<description xsi:nil="true" description>
		</topic>
	</topics>
	<users>
		<user>
			<id>1</id>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<f_name>Jess</f_name>
			<l_name>Shelton</l_name>
			<b_day>1947-10-26</b_day>
			<gender>m</gender>
			<email>JessDShelton@rhyta.com</email>
			<password>ja5ooyoo0Ie</password>
			<address>4676 Rogers Street</address>
			<city>Cincinnati</city>
			<state>OH</state>
			<zip>45231</zip>
			<phone>5135217162</phone>
			<remember_token xsi:nil="true" remember_token>
		</user>
		<user>
			<id>2</id>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<f_name>Angela</f_name>
			<l_name>Ledezma</l_name>
			<b_day>1971-06-18</b_day>
			<gender>f</gender>
			<email>AngelaALedezma@teleworm.us</email>
			<password>CeiXequae7ai</password>
			<address>2597 Half and Half Drive</address>
			<city>Fresno</city>
			<state>CA</state>
			<zip>93721</zip>
			<phone>5599042126</phone>
			<remember_token xsi:nil="true" remember_token>
		</user>
		<user>
			<id>3</id>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<f_name>Jim</f_name>
			<l_name>Cates</l_name>
			<b_day>1954-05-21</b_day>
			<gender>m</gender>
			<email>JimSCates@superrito.com</email>
			<password>Aiweew3oqu</password>
			<address>159 Green Acres Road</address>
			<city>Manteo</city>
			<state>NC</state>
			<zip>27954</zip>
			<phone>2524734138</phone>
			<remember_token xsi:nil="true" remember_token>
		</user>
		<user>
			<id>4</id>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<f_name>April</f_name>
			<l_name>Bohn</l_name>
			<b_day>1961-07-24</b_day>
			<gender>f</gender>
			<email>AprilPBohn@rhyta.com</email>
			<password>Ra6cohy7L</password>
			<address>219 Virgil Street</address>
			<city>Panama City</city>
			<state>FL</state>
			<zip>32401</zip>
			<phone>8502527923</phone>
			<remember_token xsi:nil="true" remember_token>
		</user>
		<user>
			<id>5</id>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<f_name>Natalie</f_name>
			<l_name>Elswick</l_name>
			<b_day>1967-02-19</b_day>
			<gender>f</gender>
			<email>NatalieDElswick@fleckens.hu</email>
			<password>tiemo5ahQuae</password>
			<address>236 Cunningham Court</address>
			<city>Detroit</city>
			<state>MI</state>
			<zip>48226</zip>
			<phone>2486975059</phone>
			<remember_token xsi:nil="true" remember_token>
		</user>
		<user>
			<id>6</id>
			<created_at>2014-11-12</created_at>
			<updated_at>2014-11-12</updated_at>
			<f_name>Sylvia</f_name>
			<l_name>Meehan</l_name>
			<b_day>1982-08-30</b_day>
			<gender>f</gender>
			<email>SylviaAMeehan@dayrep.com</email>
			<password>Ooyemoo4</password>
			<address>1838 Wiseman Street</address>
			<city>Knoxville</city>
			<state>TN</state>
			<zip>37909</zip>
			<phone>8653820337</phone>
			<remember_token xsi:nil="true" remember_token>
		</user>
		<user>
			<id>7</id>